language: node_js
node_js:
- 12
install: npm install
scripts:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_8c85dd6757cc_key -iv $encrypted_8c85dd6757cc_iv
  -in deploy.enc -out ./deploy -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy
- echo -e "Host 3.8.141.48\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy
- npm install pm2 -g
- pm2 deploy ecosystem.config.js production update

