language: node_js
node_js:
- 12
install: npm install
scripts:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_8c85dd6757cc_key -iv $encrypted_8c85dd6757cc_iv
  -in deploy.enc -out ./deploy -d
